CREATE TABLE [staging].[genius_ClaimMart] (
    [UniqueID]              INT              NOT NULL,
    [LOBCode]               NVARCHAR (4)     NULL,
    [LOB]                   NVARCHAR (30)    NULL,
    [Class2]                NVARCHAR (8)     NULL,
    [ClaimNumber]           DECIMAL (9)      NULL,
    [ParentRef]             NUMERIC (9)      NULL,
    [ClaimRef]              NVARCHAR (15)    NULL,
    [Level]                 NVARCHAR (7)     NOT NULL,
    [OpenDate]              DATE             NULL,
    [CloseDate]             DATE             NULL,
    [UpdateDate]            DATE             NULL,
    [PolicyReference]       NVARCHAR (15)    NULL,
    [MasterNumber]          NVARCHAR (6)     NULL,
    [MasterSequence]        NVARCHAR (3)     NULL,
    [ContractTitle]         NVARCHAR (30)    NULL,
    [ClaimMaster]           DECIMAL (9)      NULL,
    [Company]               NVARCHAR (8)     NULL,
    [Branch]                NVARCHAR (8)     NULL,
    [BranchDescription]     NVARCHAR (25)    NULL,
    [ClaimStatus]           NVARCHAR (6)     NOT NULL,
    [ClaimStatusDtl]        NVARCHAR (7)     NOT NULL,
    [ClaimType]             NVARCHAR (13)    NOT NULL,
    [CatCode]               NVARCHAR (8)     NULL,
    [UWY]                   DECIMAL (5)      NULL,
    [TreatyType]            NVARCHAR (3)     NULL,
    [TreatyTypeDescription] NVARCHAR (30)    NULL,
    [Class1Code]            NVARCHAR (4)     NULL,
    [ClassofBusiness]       NVARCHAR (30)    NULL,
    [ReportingUnitCode]     NVARCHAR (3)     NULL,
    [ReportingUnit]         NVARCHAR (30)    NULL,
    [Underwriter]           NVARCHAR (25)    NULL,
    [UWBroker]              NVARCHAR (25)    NULL,
    [UWBrokerGroup]         NVARCHAR (78)    NULL,
    [CLMBroker]             NVARCHAR (25)    NULL,
    [CLMBrokerGroup]        NVARCHAR (78)    NULL,
    [ClaimHandler]          NVARCHAR (25)    NULL,
    [Territory]             NVARCHAR (30)    NULL,
    [Area1]                 NVARCHAR (30)    NULL,
    [Area2]                 NVARCHAR (30)    NULL,
    [Program]               NVARCHAR (15)    NULL,
    [EventDate]             DATE             NULL,
    [EntryDate]             DATE             NULL,
    [ReportingPeriod]       DECIMAL (5)      NULL,
    [Cedant]                NVARCHAR (100)   NULL,
    [Insured]               NVARCHAR (25)    NULL,
    [Claimant]              NVARCHAR (45)    NULL,
    [LossType]              NVARCHAR (15)    NULL,
    [MajorLoss]             NVARCHAR (15)    NULL,
    [Limit]                 DECIMAL (15)     NULL,
    [Excess]                DECIMAL (15)     NULL,
    [Share]                 DECIMAL (11, 7)  NULL,
    [TmrLimit]              DECIMAL (31, 11) NULL,
    [TransDate]             DATE             NULL,
    [Currency]              NVARCHAR (3)     NULL,
    [OCCClaimCurrency]      NVARCHAR (3)     NULL,
    [ACCClaimCurrency]      NVARCHAR (3)     NULL,
    [BCCClaimCurrency]      NVARCHAR (3)     NOT NULL,
    [ABRate]                DECIMAL (15, 8)  NULL,
    [OARate]                DECIMAL (15, 8)  NULL,
    [OBRate]                DECIMAL (15, 8)  NULL,
    [RI]                    NVARCHAR (6)     NULL,
    [RIMS]                  NVARCHAR (3)     NULL,
    [LossBrokerRef2]        NVARCHAR (15)    NULL,
    [TSMCompany]            NVARCHAR (1)     NOT NULL,
    [OrigLossesPaid]        DECIMAL (15, 2)  NULL,
    [AccLossesPaid]         DECIMAL (15, 2)  NULL,
    [BaseLossesPaid]        DECIMAL (15, 2)  NULL,
    [OrigOutstanding]       DECIMAL (15, 2)  NULL,
    [AccOutstanding]        DECIMAL (15, 2)  NULL,
    [BaseOutstanding]       DECIMAL (15, 2)  NULL,
    [OrigFGUOutstanding]    DECIMAL (15, 2)  NULL,
    [AccFGUOutstanding]     DECIMAL (15, 2)  NULL,
    [BaseFGUOutstanding]    DECIMAL (15, 2)  NULL,
    [OrigFGUPaid]           DECIMAL (15, 2)  NULL,
    [AccFGUPaid]            DECIMAL (15, 2)  NULL,
    [BaseFGUPaid]           DECIMAL (15, 2)  NULL,
    [OrigExpense]           DECIMAL (15, 2)  NULL,
    [AccExpense]            DECIMAL (15, 2)  NULL,
    [BaseExpense]           DECIMAL (15, 2)  NULL,
    [OrigExpenseRes]        DECIMAL (15, 2)  NULL,
    [AccExpenseRes]         DECIMAL (15, 2)  NULL,
    [BaseExpenseRes]        DECIMAL (15, 2)  NULL,
    [OrigIBNR]              DECIMAL (15, 2)  NULL,
    [AccIBNR]               DECIMAL (15, 2)  NULL,
    [BaseIBNR]              DECIMAL (15, 2)  NULL,
    [OrigACR]               DECIMAL (15, 2)  NULL,
    [AccACR]                DECIMAL (15, 2)  NULL,
    [BaseACR]               DECIMAL (15, 2)  NULL,
    [OrigAER]               DECIMAL (15, 2)  NULL,
    [AccAER]                DECIMAL (15, 2)  NULL,
    [BaseAER]               DECIMAL (15, 2)  NULL,
    [OrigCededLossesPaid]   DECIMAL (15, 2)  NULL,
    [AccCededLossesPaid]    DECIMAL (15, 2)  NULL,
    [BaseCededLossesPaid]   DECIMAL (15, 2)  NULL,
    [OrigCededOutstanding]  DECIMAL (15, 2)  NULL,
    [AccCededOutstanding]   DECIMAL (15, 2)  NULL,
    [BaseCededOutstanding]  DECIMAL (15, 2)  NULL,
    [OrigCededExpense]      DECIMAL (15, 2)  NULL,
    [AccCededExpense]       DECIMAL (15, 2)  NULL,
    [BaseCededExpense]      DECIMAL (15, 2)  NULL,
    [OrigCededExpenseRes]   DECIMAL (15, 2)  NULL,
    [AccCededExpenseRes]    DECIMAL (15, 2)  NULL,
    [BaseCededExpenseRes]   DECIMAL (15, 2)  NULL,
    [OrigCededIBNR]         DECIMAL (15, 2)  NULL,
    [AccCededIBNR]          DECIMAL (15, 2)  NULL,
    [BaseCededIBNR]         DECIMAL (15, 2)  NULL,
    [OrigCededACR]          DECIMAL (15, 2)  NULL,
    [AccCededACR]           DECIMAL (15, 2)  NULL,
    [BaseCededACR]          DECIMAL (15, 2)  NULL,
    [OrigCededAER]          DECIMAL (15, 2)  NULL,
    [AccCededAER]           DECIMAL (15, 2)  NULL,
    [BaseCededAER]          DECIMAL (15, 2)  NULL,
    CONSTRAINT [PK_genius_ClaimMartid] PRIMARY KEY CLUSTERED ([UniqueID] ASC)
);

