CREATE TABLE [staging].[Layer_PL_Priced] (
    [pricing_id]                                                     INT              NULL,
    [CtSeriesID]                                                     INT              NULL,
    [SubmissionID]                                                   UNIQUEIDENTIFIER NULL,
    [Contract_Currency]                                              NVARCHAR (3)     NULL,
    [Limit_Orig_Priced]                                              MONEY            NULL,
    [Retention_Orig_Priced]                                          MONEY            NULL,
    [Reinstatements_Priced]                                          NVARCHAR (50)    NULL,
    [No_Claims_Bonus_Orig_Priced]                                    FLOAT (53)       NULL,
    [AAD_Orig_Priced]                                                MONEY            NULL,
    [Subject_Premium_Orig_Priced]                                    MONEY            NULL,
    [Rate_On_Line_Priced]                                            FLOAT (53)       NULL,
    [Rate_On_EPI_Priced]                                             FLOAT (53)       NULL,
    [Cession_Priced]                                                 FLOAT (53)       NULL,
    [100_RI_Written_Premium_Orig_Priced]                             MONEY            NULL,
    [TMR_Share_Percent_Priced]                                       FLOAT (53)       NULL,
    [Share_Basis_Priced]                                             NVARCHAR (50)    NULL,
    [TMR_Share_Of_100_Percent_Priced]                                FLOAT (53)       NULL,
    [Written_Premium_Priced]                                         MONEY            NULL,
    [Expected_Reinst_Premium_Priced]                                 MONEY            NULL,
    [Swing_Premium_Priced]                                           MONEY            NULL,
    [No_Claims_Bonus_Impact_Priced]                                  MONEY            NULL,
    [Final_Expected_Premium_Priced]                                  MONEY            NULL,
    [Discounted_Final_Expected_Premium_Priced]                       MONEY            NULL,
    [Before_Treaty_Features_Priced]                                  MONEY            NULL,
    [Eliminated_By_AAD_Priced]                                       MONEY            NULL,
    [Eliminated_By_Caps_And_Limit_Priced]                            MONEY            NULL,
    [Eliminated_By_NCB_Priced]                                       MONEY            NULL,
    [Final_Expected_Losses_Priced]                                   MONEY            NULL,
    [Discounted_Final_Expected_Losses_Priced]                        MONEY            NULL,
    [Attritional_Loss_Ratio_Priced]                                  FLOAT (53)       NULL,
    [Large_Loss_Ratio_Priced]                                        FLOAT (53)       NULL,
    [Nat_Cat_Event_Based_Loss_Ratio_Priced]                          FLOAT (53)       NULL,
    [Nat_Cat_Non_Event_Based_Loss_Ratio_Priced]                      FLOAT (53)       NULL,
    [Man_Made_Loss_Ratio_Priced]                                     FLOAT (53)       NULL,
    [Total_Loss_Ratio_Priced]                                        FLOAT (53)       NULL,
    [Discounted_Loss_Ratio_Priced]                                   FLOAT (53)       NULL,
    [Pure_Rate_Priced]                                               FLOAT (53)       NULL,
    [Multiple_Priced]                                                FLOAT (53)       NULL,
    [Brokerage_Percent_Priced]                                       FLOAT (53)       NULL,
    [Provisional_Commission_Percent_Priced]                          MONEY            NULL,
    [Adjustable_Commission_Percent_Priced]                           FLOAT (53)       NULL,
    [Premium_Other_Acq_Percent_Priced]                               FLOAT (53)       NULL,
    [Total_Other_Acq_Percent_Priced]                                 FLOAT (53)       NULL,
    [Discounted_Other_Acq_Percent_Priced]                            FLOAT (53)       NULL,
    [Loss_Of_Investment_Income_Expense_Priced]                       MONEY            NULL,
    [Technical_Combined_Ratio_Priced]                                FLOAT (53)       NULL,
    [Discounted_Technical_Combined_Ratio_Priced]                     FLOAT (53)       NULL,
    [Management_Expense_Ratio_Priced]                                FLOAT (53)       NULL,
    [Combined_Ratio_Priced]                                          FLOAT (53)       NULL,
    [Discounted_Combined_Ratio_Priced]                               FLOAT (53)       NULL,
    [Undiscounted_Profit_Excl_Management_Exp_Priced]                 MONEY            NULL,
    [Discounted_Profit_Excl_Management_Exp_Priced]                   MONEY            NULL,
    [Undiscounted_Profit_Priced]                                     MONEY            NULL,
    [Discounted_Profit_Priced]                                       MONEY            NULL,
    [Investment_Income_Priced]                                       MONEY            NULL,
    [Loss_Discount_Factor_Priced]                                    FLOAT (53)       NULL,
    [Marginal_Capital_Priced]                                        MONEY            NULL,
    [Marginal_ROR_Priced]                                            FLOAT (53)       NULL,
    [Allocated_Capital_Priced]                                       MONEY            NULL,
    [Allocated_Capital_Premium_Ratio_Priced]                         FLOAT (53)       NULL,
    [Allocated_ROR_Excl_Management_Exp_Priced]                       FLOAT (53)       NULL,
    [Allocated_ROR_Priced]                                           FLOAT (53)       NULL,
    [Economic_Value_Added_Priced]                                    MONEY            NULL,
    [Steering_Bucket_Priced]                                         INT              NULL,
    [Probability_Undiscounted_UW_Loss_Excl_Management_Exp_Priced]    FLOAT (53)       NULL,
    [Probability_Discounted_UW_Loss_Excl_Management_Exp_Priced]      FLOAT (53)       NULL,
    [Probability_No_Loss_Priced]                                     FLOAT (53)       NULL,
    [Coefficient_of_Variation_Loss_Dist_Pre_Treaty_Features_Priced]  FLOAT (53)       NULL,
    [Coefficient_of_Variation_Loss_Dist_Post_Treaty_Features_Priced] FLOAT (53)       NULL,
    [First_Event_Attachment_Probability_Priced]                      FLOAT (53)       NULL,
    [First_Event_Exhaustion_Probability_Priced]                      FLOAT (53)       NULL,
    [Second_Event_Attachment_Probability_Priced]                     FLOAT (53)       NULL,
    [Second_Event_Exhaustion_Probability_Priced]                     FLOAT (53)       NULL,
    [Third_Event_Attachment_Probability_Priced]                      FLOAT (53)       NULL,
    [Third_Event_Exhaustion_Probability_Priced]                      FLOAT (53)       NULL,
    [Fourth_Event_Attachment_Probability_Priced]                     FLOAT (53)       NULL,
    [Fourth_Event_Exhaustion_Probability_Priced]                     FLOAT (53)       NULL,
    [UW_Risk_Priced]                                                 MONEY            NULL,
    [Marginal_UW_Risk_Priced]                                        MONEY            NULL,
    [Net_Profit_Marginal_1_in_20_VaR_Priced]                         MONEY            NULL,
    [US_HU_Exposure_Profit_Excl_Management_Exp_Priced]               MONEY            NULL,
    [US_HU_Contribution_Profit_Excl_Management_Exp_Priced]           MONEY            NULL,
    [US_HU_Exposure_Loss_Priced]                                     MONEY            NULL,
    [US_HU_Contribution_Loss_Priced]                                 MONEY            NULL,
    [Standalone_Profit_VaR_2500_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_5000_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_7500_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9000_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9500_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9800_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9900_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9950_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9960_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9990_Priced]                              MONEY            NULL,
    [Standalone_Profit_VaR_9995_Priced]                              MONEY            NULL,
    [Occ_Limit_Priced]                                               MONEY            NULL,
    [UW_Capacity_Modelled_Downside_Priced]                           MONEY            NULL,
    [UW_Capacity_Priced]                                             MONEY            NULL,
    [Maximum_Downside_Priced]                                        MONEY            NULL
);

