CREATE TABLE [staging].[ICDCREP] (
    [rid]     INT           IDENTITY (1, 1) NOT NULL,
    [IDTAJK]  NVARCHAR (1)  NULL,
    [IDTAJM]  NVARCHAR (10) NULL,
    [IDTAMS]  NVARCHAR (1)  NULL,
    [IDTAJN]  NVARCHAR (1)  NULL,
    [IDTAJO]  NVARCHAR (1)  NULL,
    [IDTAJP]  NVARCHAR (1)  NULL,
    [IDTAJQ]  NVARCHAR (1)  NULL,
    [IADDCD]  NVARCHAR (6)  NULL,
    [IADDDS]  NVARCHAR (30) NULL,
    [IADDSD]  NVARCHAR (11) NULL,
    [IAVYFG]  NVARCHAR (1)  NULL,
    [IAVYPG]  NVARCHAR (6)  NULL,
    [IAAMCD]  NVARCHAR (3)  NULL,
    [IADDOY]  NVARCHAR (1)  NULL,
    [IARCFD]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL,
    PRIMARY KEY CLUSTERED ([rid] ASC)
);

