CREATE TABLE [staging].[ZAB8DF00] (
    [B8CNCD] NVARCHAR (8)  NULL,
    [B8SQTX] NVARCHAR (5)  NULL,
    [B8MBST] NVARCHAR (1)  NULL,
    [B8MCST] NVARCHAR (1)  NULL,
    [B8MDST] NVARCHAR (1)  NULL,
    [B8MEST] NVARCHAR (1)  NULL,
    [B8MFST] NVARCHAR (1)  NULL,
    [B8MGST] NVARCHAR (1)  NULL,
    [B8MHST] NVARCHAR (1)  NULL,
    [B8MIST] NVARCHAR (1)  NULL,
    [B8MJST] NVARCHAR (1)  NULL,
    [B8GBSF] NVARCHAR (10) NULL,
    [B8MKST] NVARCHAR (1)  NULL,
    [B8MLST] NVARCHAR (1)  NULL,
    [B8MMST] NVARCHAR (1)  NULL,
    [B8MNST] NVARCHAR (1)  NULL,
    [B8MOST] NVARCHAR (1)  NULL,
    [B8MPST] NVARCHAR (1)  NULL
);

