CREATE TABLE [staging].[ZABRDF00] (
    [BRO0CD] NVARCHAR (3)  NULL,
    [BRMVST] NVARCHAR (2)  NULL,
    [BRMFCD] NVARCHAR (5)  NULL,
    [BRS7TX] NVARCHAR (15) NULL,
    [BRS8TX] NVARCHAR (40) NULL,
    [BRMXNA] NVARCHAR (5)  NULL,
    [BRMYNA] NVARCHAR (5)  NULL,
    [BRS0ST] NVARCHAR (1)  NULL,
    [BRS1ST] NVARCHAR (1)  NULL,
    [BRS2ST] NVARCHAR (1)  NULL,
    [BRS3ST] NVARCHAR (1)  NULL
);

