CREATE TABLE [staging].[ZACADF00] (
    [CACNCD]  NVARCHAR (8)  NULL,
    [CACUCD]  NVARCHAR (3)  NULL,
    [CAT1TX]  NVARCHAR (15) NULL,
    [CAT8TX]  NVARCHAR (40) NULL,
    [CAM1NA]  NVARCHAR (5)  NULL,
    [CAM2NA]  NVARCHAR (5)  NULL,
    [CAGQF1]  NVARCHAR (1)  NULL,
    [CAX647]  NVARCHAR (1)  NULL,
    [CANENB]  DECIMAL (3)   NULL,
    [CAB348]  NVARCHAR (3)  NULL,
    [CAPGCD]  NVARCHAR (3)  NULL,
    [CAOSCD]  NVARCHAR (3)  NULL,
    [BuildID] INT           NULL
);

