CREATE TABLE [staging].[ZHAADF00] (
    [AAAACD]  NVARCHAR (5)  NOT NULL,
    [AARCID]  NVARCHAR (2)  NULL,
    [AAUSQ3]  NVARCHAR (3)  NULL,
    [AAAAK1]  NVARCHAR (5)  NULL,
    [AAAAK2]  NVARCHAR (5)  NULL,
    [AAAASD]  NVARCHAR (15) NULL,
    [AAAADS]  NVARCHAR (30) NULL,
    [AAAIFG]  NVARCHAR (1)  NULL,
    [AAA1C@]  NVARCHAR (5)  NULL,
    [AAA2C@]  NVARCHAR (5)  NULL,
    [AAA3C@]  NVARCHAR (5)  NULL,
    [AAAAF1]  NVARCHAR (1)  NULL,
    [AAAAF2]  NVARCHAR (1)  NULL,
    [AAAAF3]  NVARCHAR (1)  NULL,
    [AAAAF4]  NVARCHAR (1)  NULL,
    [AAGPFG]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

