CREATE TABLE [staging].[ZHAVDF00] (
    [AVVLCD]  NVARCHAR (2)  NOT NULL,
    [AVAVCD]  NVARCHAR (1)  NOT NULL,
    [AVUSQ5]  NVARCHAR (5)  NULL,
    [AVRCID]  NVARCHAR (2)  NULL,
    [AVAVDS]  NVARCHAR (30) NULL,
    [AVAVSD]  NVARCHAR (15) NULL,
    [AVAVC1]  NVARCHAR (5)  NULL,
    [AVAVC2]  NVARCHAR (5)  NULL,
    [AVAVF1]  NVARCHAR (1)  NULL,
    [AVAVF2]  NVARCHAR (1)  NULL,
    [AVAVF3]  NVARCHAR (1)  NULL,
    [AVAVF4]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

