CREATE TABLE [staging].[ZHCVDF00] (
    [CVVG01]  NVARCHAR (2)  NULL,
    [CVV243]  NVARCHAR (4)  NULL,
    [CVRCID]  NVARCHAR (2)  NULL,
    [CVV235]  NVARCHAR (30) NULL,
    [CVV236]  NVARCHAR (15) NULL,
    [CVV237]  NVARCHAR (5)  NULL,
    [CVV238]  NVARCHAR (5)  NULL,
    [CVV239]  NVARCHAR (1)  NULL,
    [CVV240]  NVARCHAR (1)  NULL,
    [CVV241]  NVARCHAR (1)  NULL,
    [CVV242]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

