CREATE TABLE [staging].[ZHDPDF00] (
    [DPDPCD]  NVARCHAR (3)  NOT NULL,
    [DPUSQ5]  NVARCHAR (5)  NULL,
    [DPRCID]  NVARCHAR (2)  NULL,
    [DPDPDS]  NVARCHAR (30) NULL,
    [DPDPSD]  NVARCHAR (15) NULL,
    [DPDPC1]  NVARCHAR (5)  NULL,
    [DPDPC2]  NVARCHAR (5)  NULL,
    [DPDPF1]  NVARCHAR (1)  NULL,
    [DPDPF2]  NVARCHAR (1)  NULL,
    [DPDPF3]  NVARCHAR (1)  NULL,
    [DPDPF4]  NVARCHAR (1)  NULL,
    [DPDP01]  NVARCHAR (10) NULL,
    [DPDP02]  NVARCHAR (10) NULL,
    [DPDP03]  NVARCHAR (20) NULL,
    [DPDP04]  NVARCHAR (10) NULL,
    [BuildID] INT           NULL
);

