CREATE TABLE [staging].[ZHESDF00] (
    [ESESSG]  DECIMAL (7)   NULL,
    [ESESST]  NVARCHAR (1)  NULL,
    [ESESA1]  NVARCHAR (15) NULL,
    [ESESA2]  NVARCHAR (15) NULL,
    [ESESA3]  NVARCHAR (15) NULL,
    [ESESA4]  NVARCHAR (15) NULL,
    [ESESF1]  NVARCHAR (1)  NULL,
    [ESESF2]  NVARCHAR (1)  NULL,
    [ESESF3]  NVARCHAR (1)  NULL,
    [ESESF4]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

