CREATE TABLE [staging].[ZHLHDF00] (
    [LHG8CD]  NVARCHAR (2)  NULL,
    [LHC8CD]  NVARCHAR (8)  NULL,
    [LHC8LN]  NVARCHAR (50) NULL,
    [LHC8SN]  NVARCHAR (15) NULL,
    [LHC8H1]  NVARCHAR (5)  NULL,
    [LHC8H2]  NVARCHAR (5)  NULL,
    [LHC8F1]  NVARCHAR (1)  NULL,
    [LHC8F2]  NVARCHAR (1)  NULL,
    [LHC8F3]  NVARCHAR (1)  NULL,
    [LHC8F4]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

