CREATE TABLE [staging].[ZHMJDF00] (
    [MJMJCD]  NVARCHAR (3)  NULL,
    [MJUSQ5]  NVARCHAR (5)  NULL,
    [MJRCID]  NVARCHAR (2)  NULL,
    [MJMJDS]  NVARCHAR (30) NULL,
    [MJMJSD]  NVARCHAR (15) NULL,
    [MJMJC1]  NVARCHAR (5)  NULL,
    [MJMJC2]  NVARCHAR (5)  NULL,
    [MJMAIT]  NVARCHAR (1)  NULL,
    [MJMJF1]  NVARCHAR (1)  NULL,
    [MJMJF2]  NVARCHAR (1)  NULL,
    [MJMJF3]  NVARCHAR (1)  NULL,
    [MJMJF4]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

