CREATE TABLE [staging].[ZHREDF00] (
    [RERECD]  NVARCHAR (3)  NOT NULL,
    [REUSQ5]  NVARCHAR (50) NULL,
    [RERCID]  NVARCHAR (2)  NULL,
    [REREDS]  NVARCHAR (30) NULL,
    [RERESD]  NVARCHAR (15) NULL,
    [REREC1]  NVARCHAR (5)  NULL,
    [REREC2]  NVARCHAR (5)  NULL,
    [REREF1]  NVARCHAR (1)  NULL,
    [REREF2]  NVARCHAR (1)  NULL,
    [REREF3]  NVARCHAR (1)  NULL,
    [REREF4]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

