CREATE TABLE [staging].[ZHT1DF00] (
    [T1T1CD]  NVARCHAR (4)  NULL,
    [T1USQ4]  NVARCHAR (4)  NULL,
    [T1RCID]  NVARCHAR (2)  NULL,
    [T1T1SD]  NVARCHAR (15) NULL,
    [T1T1DS]  NVARCHAR (30) NULL,
    [T1T1C1]  NVARCHAR (5)  NULL,
    [T1T1C2]  NVARCHAR (5)  NULL,
    [T1T1F1]  NVARCHAR (1)  NULL,
    [T1T1F2]  NVARCHAR (1)  NULL,
    [T1T1F3]  NVARCHAR (1)  NULL,
    [T1T1F4]  NVARCHAR (1)  NULL,
    [T1GPFG]  NVARCHAR (1)  NULL,
    [BuildID] INT           NULL
);

