CREATE TABLE [staging].[ZKELDF00] (
    [rid]     INT          IDENTITY (1, 1) NOT NULL,
    [ELFANO]  NUMERIC (9)  NULL,
    [ELFBCD]  NUMERIC (3)  NULL,
    [ELEDSG]  NUMERIC (9)  NULL,
    [ELCEXD]  NVARCHAR (8) NULL,
    [ELEL01]  NVARCHAR (1) NULL,
    [ELEL02]  NVARCHAR (1) NULL,
    [ELEL03]  NVARCHAR (1) NULL,
    [ELEL04]  NVARCHAR (1) NULL,
    [ELEL05]  NVARCHAR (1) NULL,
    [ELEL06]  NVARCHAR (1) NULL,
    [ELEL07]  NVARCHAR (1) NULL,
    [ELEL08]  NVARCHAR (1) NULL,
    [ELEL09]  NVARCHAR (1) NULL,
    [ELEL10]  NVARCHAR (1) NULL,
    [BuildID] INT          NULL,
    PRIMARY KEY CLUSTERED ([rid] ASC)
);

