CREATE TABLE [staging].[ZNNUDF00] (
    [NUNACD]  NVARCHAR (8) NOT NULL,
    [NUNUCD]  NVARCHAR (3) NOT NULL,
    [NUADCD]  DECIMAL (9)  NOT NULL,
    [NUNQSQ]  NVARCHAR (3) NULL,
    [NUU1CD]  NVARCHAR (2) NULL,
    [NUU2CD]  NVARCHAR (2) NULL,
    [NUCOCD]  DECIMAL (1)  NULL,
    [NULECD]  DECIMAL (1)  NULL,
    [NUACID]  NVARCHAR (3) NULL,
    [NUSBCD]  NVARCHAR (1) NULL,
    [BuildID] INT          NULL
);

