CREATE TABLE [staging].[ZNNXDF00] (
    [rid]     INT           IDENTITY (1, 1) NOT NULL,
    [NXNACD]  NVARCHAR (8)  NULL,
    [NXEDSG]  NUMERIC (9)   NULL,
    [NXNTF1]  NVARCHAR (78) NULL,
    [NXNTF2]  NVARCHAR (78) NULL,
    [NXNTF3]  NVARCHAR (78) NULL,
    [NXNTF4]  NVARCHAR (78) NULL,
    [NXNTS1]  NVARCHAR (1)  NULL,
    [NXNTS2]  NVARCHAR (1)  NULL,
    [NXNTE3]  NVARCHAR (1)  NULL,
    [NXNTS4]  NVARCHAR (1)  NULL,
    [NXNTS5]  NVARCHAR (1)  NULL,
    [NXNTS6]  NVARCHAR (1)  NULL,
    [NXNTS7]  NVARCHAR (1)  NULL,
    [NXNTS8]  NVARCHAR (1)  NULL,
    [NXNTS9]  NVARCHAR (1)  NULL,
    [NXNTS0]  NVARCHAR (1)  NULL,
    [NXCF1F]  NVARCHAR (78) NULL,
    [NXCF2F]  NVARCHAR (78) NULL,
    [BuildID] INT           NULL,
    PRIMARY KEY CLUSTERED ([rid] ASC)
);

