CREATE TABLE [staging].[ZSBUDF00] (
    [BUOOCD] NUMERIC (7)     NULL,
    [BUCNCD] NVARCHAR (8)    NULL,
    [BUCUCD] NVARCHAR (3)    NULL,
    [BUMPNB] NUMERIC (9)     NULL,
    [BUSQTX] NVARCHAR (5)    NULL,
    [BUENUS] NVARCHAR (10)   NULL,
    [BUADDT] NUMERIC (7)     NULL,
    [BUETIM] NUMERIC (6)     NULL,
    [BUUEST] NVARCHAR (1)    NULL,
    [BUTPST] NVARCHAR (1)    NULL,
    [BUTQST] NVARCHAR (1)    NULL,
    [BUNRGU] NUMERIC (9)     NULL,
    [BUTRST] NVARCHAR (1)    NULL,
    [BURVAC] NUMERIC (7)     NULL,
    [BUTSST] NVARCHAR (1)    NULL,
    [BUTTST] NVARCHAR (1)    NULL,
    [BUTUST] NVARCHAR (1)    NULL,
    [BUTVST] NVARCHAR (1)    NULL,
    [BUTWST] NVARCHAR (1)    NULL,
    [BUAYVA] NUMERIC (15, 2) NULL,
    [BUAZVA] NUMERIC (15, 2) NULL
);

