CREATE TABLE [staging].[ZSE1DF00] (
    [E1E0CD]  INT             NOT NULL,
    [E1E1V1]  NVARCHAR (10)   NULL,
    [E1JBUS]  NVARCHAR (10)   NULL,
    [E1E1X1]  DECIMAL (15, 8) NULL,
    [E1E1O1]  NVARCHAR (1)    NULL,
    [E1E1X2]  DECIMAL (15, 8) NULL,
    [E1E1O2]  NVARCHAR (1)    NULL,
    [E1E1D1]  DECIMAL (7)     NULL,
    [E1E1D2]  DECIMAL (7)     NULL,
    [E1E1D3]  DECIMAL (7)     NULL,
    [E1E1PS]  NVARCHAR (1)    NULL,
    [E1QTIN]  DECIMAL (3)     NULL,
    [E1DUDT]  DECIMAL (7)     NULL,
    [E1E1DS]  NVARCHAR (25)   NULL,
    [E1E1FA]  NVARCHAR (1)    NULL,
    [E1E1FB]  NVARCHAR (1)    NULL,
    [E1E1FC]  NVARCHAR (1)    NULL,
    [E1E1FD]  NVARCHAR (1)    NULL,
    [E1E1F1]  NVARCHAR (1)    NULL,
    [E1E1F2]  NVARCHAR (1)    NULL,
    [E1E1F3]  NVARCHAR (1)    NULL,
    [E1E1F4]  NVARCHAR (1)    NULL,
    [E1E1F5]  NVARCHAR (1)    NULL,
    [E1E1F6]  NVARCHAR (1)    NULL,
    [E1E1F7]  NVARCHAR (1)    NULL,
    [E1E1F8]  NVARCHAR (1)    NULL,
    [BuildID] INT             NULL,
    CONSTRAINT [PK_StagingZSE1DF00_E1E0CD] PRIMARY KEY CLUSTERED ([E1E0CD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCINDX_StagZSE1_E1E1D2]
    ON [staging].[ZSE1DF00]([E1E1D2] ASC);

