CREATE TABLE [staging].[ZSE3DF00] (
    [rid]     INT             IDENTITY (1, 1) NOT NULL,
    [E3E0CD]  DECIMAL (9)     NULL,
    [E3E2CD]  DECIMAL (3)     NULL,
    [E3E3CD]  DECIMAL (3)     NULL,
    [E3E6CD]  DECIMAL (3)     NULL,
    [E3GPMT]  NVARCHAR (1)    NULL,
    [E3SPPN]  NVARCHAR (8)    NULL,
    [E3SPSP]  DECIMAL (11, 7) NULL,
    [E3E4CD]  DECIMAL (3)     NULL,
    [E3AMCD]  NVARCHAR (3)    NULL,
    [E3E3TG]  DECIMAL (3)     NULL,
    [E3E3A1]  DECIMAL (15, 2) NULL,
    [E3E3A2]  DECIMAL (15, 2) NULL,
    [E3E3A3]  DECIMAL (15, 2) NULL,
    [E3E3SF]  NVARCHAR (1)    NULL,
    [E3E3F1]  NVARCHAR (1)    NULL,
    [E3E3F2]  NVARCHAR (1)    NULL,
    [E3E3F3]  NVARCHAR (1)    NULL,
    [E3E3F4]  NVARCHAR (1)    NULL,
    [E3E3F5]  NVARCHAR (1)    NULL,
    [E3E3F6]  NVARCHAR (1)    NULL,
    [E3E3F7]  NVARCHAR (1)    NULL,
    [E3E3F8]  NVARCHAR (1)    NULL,
    [BuildID] INT             NULL,
    PRIMARY KEY CLUSTERED ([rid] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCINDX_stagingZSE3DF00_E3E0CD_E3E2CD_E3E3CD]
    ON [staging].[ZSE3DF00]([E3E0CD] ASC, [E3E2CD] ASC, [E3E3CD] ASC);

