CREATE TABLE [staging].[ZSE4DF00] (
    [E4E0CD]  DECIMAL (9)  NULL,
    [E4E2CD]  DECIMAL (3)  NULL,
    [E4E4CD]  DECIMAL (3)  NULL,
    [E4RIMN]  NVARCHAR (6) NULL,
    [E4RIMS]  NVARCHAR (3) NULL,
    [E4RISS]  NVARCHAR (2) NULL,
    [E4RIFC]  NVARCHAR (1) NULL,
    [E4SSRI]  NVARCHAR (1) NULL,
    [E4E4F1]  NVARCHAR (1) NULL,
    [E4E4F2]  NVARCHAR (1) NULL,
    [E4E4F3]  NVARCHAR (1) NULL,
    [E4E4F4]  NVARCHAR (1) NULL,
    [E4E4F5]  NVARCHAR (1) NULL,
    [E4E4F6]  NVARCHAR (1) NULL,
    [E4E4F7]  NVARCHAR (1) NULL,
    [E4E4F8]  NVARCHAR (1) NULL,
    [BuildID] INT          NULL
);

