CREATE TABLE [staging].[ZUDVDF00] (
    [DVMANU]  NVARCHAR (6) NULL,
    [DVMASE]  NVARCHAR (3) NULL,
    [DVDGSQ]  NVARCHAR (3) NULL,
    [DVDGVS]  NVARCHAR (3) NULL,
    [DVDVSD]  NUMERIC (7)  NULL,
    [DVDVED]  NUMERIC (7)  NULL,
    [DVDGMS]  NVARCHAR (1) NULL,
    [DVCBEN]  NVARCHAR (3) NULL,
    [DVDGS1]  NUMERIC (9)  NULL,
    [DVDGS2]  NUMERIC (9)  NULL,
    [DVDGC1]  NVARCHAR (8) NULL,
    [DVDGC2]  NVARCHAR (8) NULL,
    [BuildID] INT          NULL
);

