CREATE TABLE [staging].[zueldf00] (
    [ELMANU] NVARCHAR (6) NULL,
    [ELMASE] NVARCHAR (3) NULL,
    [ELEDNO] NVARCHAR (3) NULL,
    [ELELNC] NUMERIC (9)  NULL,
    [ELETCD] NVARCHAR (3) NULL,
    [ELELAN] NVARCHAR (8) NULL,
    [ELELED] NUMERIC (7)  NULL,
    [ELELST] NUMERIC (7)  NULL,
    [ELDTSE] NUMERIC (7)  NULL,
    [ELELAF] NVARCHAR (1) NULL,
    [ELELRI] NVARCHAR (1) NULL,
    [ELELMS] NVARCHAR (1) NULL
);

