CREATE TABLE [staging].[ZUIEDF00] (
    [IEMANU]  NVARCHAR (6) NULL,
    [IEMASE]  NVARCHAR (3) NULL,
    [IEIESG]  DECIMAL (5)  NULL,
    [IER1PR]  DECIMAL (9)  NULL,
    [IEIEPT]  NVARCHAR (1) NULL,
    [IEIEF1]  NVARCHAR (1) NULL,
    [IEIEF2]  NVARCHAR (1) NULL,
    [IEIEF3]  NVARCHAR (1) NULL,
    [IEIEF4]  NVARCHAR (1) NULL,
    [BuildID] INT          NULL
);

