CREATE TABLE [staging].[ZUM0DF00] (
    [M0MANU]  NVARCHAR (6) NULL,
    [M0MASE]  NVARCHAR (3) NULL,
    [M0RKRS]  NVARCHAR (2) NULL,
    [M0SDSQ]  NVARCHAR (3) NULL,
    [M0CVSQ]  NVARCHAR (3) NULL,
    [M0EDSG]  DECIMAL (9)  NULL,
    [M0CE1F]  NVARCHAR (1) NULL,
    [M0CE2F]  NVARCHAR (1) NULL,
    [M0CE3F]  NVARCHAR (1) NULL,
    [M0CE4F]  NVARCHAR (1) NULL,
    [M0CE5F]  NVARCHAR (1) NULL,
    [M0CE6F]  NVARCHAR (1) NULL,
    [M0CE7F]  NVARCHAR (1) NULL,
    [M0CE8F]  NVARCHAR (1) NULL,
    [M0CE9F]  NVARCHAR (1) NULL,
    [M0CE0F]  NVARCHAR (1) NULL,
    [BuildID] INT          NULL
);

