CREATE TABLE [staging].[AC_LEDGER_DETAIL](
	[OBJECT_ID] [char](32) NOT NULL,
	[DTL_AMT] [numeric](22, 2) NULL,
	[DTL_UNR_AMT] [numeric](22, 2) NULL,
	[DTL_PLT_AMT] [numeric](22, 2) NULL,
	[REPLACEMENT_VALUE] [numeric](22, 2) NULL,
	[TRANS_GEN_LDGR_DT] [datetime] NULL,
	[EXCH_AMT] [numeric](22, 2) NULL,
	[FUNC_AMT2] [numeric](22, 2) NULL,
	[OCC_YR] [int] NULL,
	[ORIG_UW_YEAR] [int] NULL,
	[ORGNL_ACC_YEAR] [int] NULL,
	[UW_YEAR] [int] NULL,
	[WKST_SEQ_NBR] [numeric](10, 0) NULL,
	[IS_LIQUID] [char](1) NULL,
	[SHARE_CALC] [char](1) NULL,
	[PRODUCER] [char](4) NULL,
	[PRE_PROD] [char](4) NULL,
	[BUS_CAT] [char](2) NULL,
	[INSUR_CAT] [char](3) NULL,
	[ORGNL_FGU_AMT] [numeric](22, 2) NULL,
	[NQS_NET_PERCENT] [numeric](10, 6) NULL,
	[AC_START_DATE] [datetime] NULL,
	[AC_END_DATE] [datetime] NULL,
	[IS_IN_S_CTRL_AMT] [char](1) NULL,
	[DIS_PERCENT] [numeric](10, 6) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[TAX_PERCENT] [numeric](10, 6) NULL,
	[IS_SPECIAL] [char](1) NULL,
	[SPLIT_PER_AC] [char](1) NULL,
	[OCC_ID] [char](36) NULL,
	[IS_IN_CP_ORDER] [char](1) NULL,
	[ORIG_BOOK_YEAR] [int] NULL,
	[FK_EXCH_CURR] [char](3) NULL,
	[FRK_SETLMNT_IND] [char](15) NULL,
	[FSK_SETLMNT_IND] [int] NULL,
	[FK_DTL_COMMENT] [char](32) NULL,
	[FK_SOC] [char](32) NULL,
	[FK_INS_PER] [char](32) NULL,
	[FRK_ORGNL_ACC_PRD] [char](15) NULL,
	[FSK_ORGNL_ACC_PRD] [int] NULL,
	[FK_ACCT_CLASS] [char](32) NULL,
	[FK_WORKSHEET] [char](32) NULL,
	[FK_BALANCE] [char](32) NULL,
	[FK_ENTRY_CODE] [char](32) NULL,
	[FK_AMENDMENT] [char](32) NULL,
	[FRK_SICSNT_SYSTEM] [char](15) NULL,
	[FSK_SICSNT_SYSTEM] [int] NULL,
	[FK_CESSION] [char](32) NULL,
	[FK_ORIG_CESSION] [char](32) NULL,
	[FK_RPT_UNT] [char](32) NULL,
	[FK_CLAIM_TO_SOC] [char](32) NULL,
	[FK_INS_PER_ASSUMED] [char](32) NULL,
	[FRK_REINS_CAT] [char](15) NULL,
	[FSK_REINS_CAT] [int] NULL,
	[FK_HEADLINE_LOSS] [char](32) NULL,
	[FK_PARENT_DET] [char](32) NULL,
	[FRK_ACCESS_CODE] [char](15) NULL,
	[FSK_ACCESS_CODE] [int] NULL,
	[FK_INS_PER_NQS] [char](32) NULL,
	[FK_SRCE_INSTALMENT] [char](32) NULL,
	[FK_TAX_COUNTRY] [char](32) NULL,
	[FK_ORG_BS] [char](32) NULL,
	[FK_UDEF_DATA] [char](32) NULL,
	[FK_ORIG_RP] [char](32) NULL,
	[FRK_TAX_TYPE] [char](15) NULL,
	[FSK_TAX_TYPE] [int] NULL,
	[FRK_ORIG_BOOK_PER] [char](15) NULL,
	[FSK_ORIG_BOOK_PER] [int] NULL,
	[FK_SRCE_IPT] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[ACC_VLD_COMMENT] [varchar](200) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
