CREATE TABLE [staging].[ADDRESS](
	[OBJECT_ID] [char](32) NOT NULL,
	[CITY_NAME] [char](45) NULL,
	[UPPERCASE_CITYNAME] [char](45) NULL,
	[BUS_UNIT_NAME] [char](40) NULL,
	[ADDR_LINE_1] [char](45) NULL,
	[UPPERCASE_ADDRLIN1] [char](45) NULL,
	[ADDR_LINE_2] [char](45) NULL,
	[ADDR_LINE_3] [char](45) NULL,
	[POSTAL_CODE] [char](25) NULL,
	[UPPERCASE_POSTALCD] [char](25) NULL,
	[IS_HOME_ADDR] [char](1) NULL,
	[IS_MAIN_ADDR] [char](1) NULL,
	[IS_ACTIVE] [char](1) NULL,
	[DESCRIPTION] [char](40) NULL,
	[ADDRESS_IDENTIFIER] [char](40) NULL,
	[FRK_OFFICE_TYPE] [char](15) NULL,
	[FSK_OFFICE_TYPE] [int] NULL,
	[FK_COUNTRY] [char](32) NULL,
	[FK_PARTY] [char](32) NULL,
	[FK_STATE] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
