CREATE TABLE [staging].[CLAIM_COND_BASIS](
	[FK_CLAIM_COND] [char](32) NOT NULL,
	[FRK_CLAIM_BASIS] [char](15) NOT NULL,
	[FSK_CLAIM_BASIS] [int] NOT NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[FK_CLAIM_COND] ASC,
	[FRK_CLAIM_BASIS] ASC,
	[FSK_CLAIM_BASIS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
