CREATE TABLE [staging].[CLAIM_COND](
	[OBJECT_ID] [char](32) NOT NULL,
	[FK_EVENT_CRE] [char](32) NULL,
	[FK_EVENT_REV] [char](32) NULL,
	[IS_CURRENT_OF_IP] [char](1) NULL,
	[IS_CURRENT_OF_LCP] [char](1) NULL,
	[FK_COND_CONTAINER] [char](32) NULL,
	[FK_INSURED_PERIOD] [char](32) NULL,
	[ANNU_NO_YEARS] [int] NULL,
	[IS_ANNU_PAYMENTS] [char](1) NULL,
	[IS_ANNU_DEPOSITS] [char](1) NULL,
	[IS_INTERLOCKING] [char](1) NULL,
	[CLASS_PRIORITY] [int] NULL,
	[ORG_LOST_LIMIT] [numeric](22, 2) NULL,
	[ORG_LOST_PRIO] [numeric](22, 2) NULL,
	[IS_EX_GRA] [char](1) NULL,
	[CLM_AD_LMT_AMT] [numeric](22, 2) NULL,
	[CLM_AD_LMT_PCT] [numeric](22, 2) NULL,
	[CLM_AD_COMMENT] [char](34) NULL,
	[CLM_COOPER] [char](1) NULL,
	[LO_RA_AFTER_DT] [datetime] NULL,
	[LO_RA_BEFORE_DT] [datetime] NULL,
	[CL_RUN_OFF_DT] [datetime] NULL,
	[EX_REP_DT] [datetime] NULL,
	[RETROAC_DT] [datetime] NULL,
	[ECO_PCT] [numeric](10, 6) NULL,
	[XPL_PCT] [numeric](10, 6) NULL,
	[IS_OR_AS_EXP] [char](1) NULL,
	[IS_AD_LO_AD_EXP] [char](1) NULL,
	[AD_LO_AD_EXP_PCT] [numeric](10, 6) NULL,
	[IS_REINS_EXH_DP] [char](1) NULL,
	[IS_OWN_ACC_COV] [char](1) NULL,
	[IS_RISK_W] [char](1) NULL,
	[MIN_NO_OF_RISK] [int] NULL,
	[INC_FGU_W_OCC_REN] [char](1) NULL,
	[APP_INW_CL_LIMIT] [char](1) NULL,
	[FRK_ANNU_REDEM] [char](15) NULL,
	[FSK_ANNU_REDEM] [int] NULL,
	[FRK_ANNU_REDEM_ARR] [char](15) NULL,
	[FSK_ANNU_REDEM_ARR] [int] NULL,
	[FRK_INT_CL_TYPE] [char](15) NULL,
	[FSK_INT_CL_TYPE] [int] NULL,
	[FRK_ANNUITY_SYSTEM] [char](15) NULL,
	[FSK_ANNUITY_SYSTEM] [int] NULL,
	[FK_INT_CL_NOTE] [char](32) NULL,
	[FK_ANNU_CL_NOTE] [char](32) NULL,
	[FK_ORG_LIM_CURC] [char](3) NULL,
	[FK_ORG_PRI_CURC] [char](3) NULL,
	[FRK_ADJ_EXP_TYPE] [char](15) NULL,
	[FSK_ADJ_EXP_TYPE] [int] NULL,
	[FRK_DECL_JUDG_TYPE] [char](15) NULL,
	[FSK_DECL_JUDG_TYPE] [int] NULL,
	[DECL_AMT_AMT] [numeric](22, 2) NULL,
	[FK_DECL_AMT_CY] [char](3) NULL,
	[FK_CLM_CURR] [char](3) NULL,
	[FRK_CLM_BAS] [char](15) NULL,
	[FSK_CLM_BAS] [int] NULL,
	[FRK_CLM_SEQ] [char](15) NULL,
	[FSK_CLM_SEQ] [int] NULL,
	[FRK_ECO_TYPE] [char](15) NULL,
	[FSK_ECO_TYPE] [int] NULL,
	[FRK_XPL_TYPE] [char](15) NULL,
	[FSK_XPL_TYPE] [int] NULL,
	[ECO_AMT_AMT] [numeric](22, 2) NULL,
	[FK_ECO_AMT_CY] [char](3) NULL,
	[XPL_AMT_AMT] [numeric](22, 2) NULL,
	[FK_XPL_AMT_CY] [char](3) NULL,
	[FRK_OR_AS_EXP] [char](15) NULL,
	[FSK_OR_AS_EXP] [int] NULL,
	[LPL_PCT] [numeric](10, 6) NULL,
	[FRK_LPL_TYPE] [char](15) NULL,
	[FSK_LPL_TYPE] [int] NULL,
	[FK_GRP_LPL] [char](32) NULL,
	[LR_PCT] [numeric](10, 6) NULL,
	[FRK_LR_TYPE] [char](15) NULL,
	[FSK_LR_TYPE] [int] NULL,
	[FK_GRP_LR] [char](32) NULL,
	[FK_NOTE] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
