CREATE TABLE [staging].[CODE_VS_GROUP](
	[FK_CODE] [char](32) NOT NULL,
	[FK_GROUP] [char](32) NOT NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[FK_CODE] ASC,
	[FK_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;