CREATE TABLE [staging].[ELECTRONIC_ADDRESS](
	[OBJECT_ID] [char](32) NOT NULL,
	[TEXT_NUMBER] [varchar](254) NULL,
	[DESCRIPTION] [char](40) NULL,
	[FRK_ELEC_ADR_TYPE] [char](15) NULL,
	[FSK_ELEC_ADR_TYPE] [int] NULL,
	[FRK_OFFICE] [char](15) NULL,
	[FSK_OFFICE] [int] NULL,
	[FK_NOTE] [char](32) NULL,
	[FK_PARTY] [char](32) NULL,
	[FK_PHYS_ADR] [char](32) NULL,
	[FK_CNU_USER] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
