CREATE TABLE [staging].[ENTRY_CODE](
	[OBJECT_ID] [char](32) NOT NULL,
	[IS_ACTIVE] [char](1) NULL,
	[IS_ENTRY_COM_REQ] [char](1) NULL,
	[IS_NORMALLY_POS] [char](1) NULL,
	[IS_PAYABLE] [char](1) NULL,
	[IS_ALLOWED_ON_CLM] [char](1) NULL,
	[IS_ALLOWED_ON_TEC] [char](1) NULL,
	[IS_ALLOWED_ON_CES] [char](1) NULL,
	[IS_ALLOWED_AS_EST] [char](1) NULL,
	[IS_EXCL_FROM_RETR] [char](1) NULL,
	[IS_EXCL_FROM_MG_RC] [char](1) NULL,
	[IS_EXCL_FROM_DOC] [char](1) NULL,
	[CODE] [char](4) NULL,
	[DESCRIPTION] [char](50) NULL,
	[FORMER_ENTRY_CODE] [char](4) NULL,
	[NAME] [char](30) NULL,
	[IS_REPL_VAL_ALLWD] [char](1) NULL,
	[IS_FOR_EST_ONLY] [char](1) NULL,
	[IS_POS_ON_OUTWD] [char](1) NULL,
	[IS_REAL_ADMIN] [char](1) NULL,
	[IS_DEFAULT_IN_CW] [char](1) NULL,
	[IS_ALLOW_IN_REAC] [char](1) NULL,
	[FK_NOTE] [char](32) NULL,
	[FRK_ENTRY_SUB_CAT] [char](15) NULL,
	[FSK_ENTRY_SUB_CAT] [int] NULL,
	[FRK_SICSNT_SYSTEM] [char](15) NULL,
	[FSK_SICSNT_SYSTEM] [int] NULL,
	[VERSION] [int] NULL,
	[FRK_FGU_BOOK_GRP] [char](15) NULL,
	[FSK_FGU_BOOK_GRP] [int] NULL,
	[HAS_VLD_PRE_CHK] [char](1) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;