CREATE TABLE [staging].[LPC_CUR_LIMIT_PREM](
	[OBJECT_ID] [char](32) NOT NULL,
	[EXCH_RATE_REINSTAT] [numeric](23, 9) NULL,
	[EXCH_RATE_PREMIUM] [numeric](23, 9) NULL,
	[EXCH_RATE_LIMIT] [numeric](23, 9) NULL,
	[EXCH_RATE_EXCESS] [numeric](23, 9) NULL,
	[FK_CURRENCY] [char](3) NULL,
	[FK_CONDITION] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
