CREATE TABLE [staging].[LPC_LIMIT](
	[OBJECT_ID] [char](32) NOT NULL,
	[FRK_OPTIONAL_FIELD] [char](15) NULL,
	[FSK_OPTIONAL_FIELD] [int] NULL,
	[FRK_CONDITION_PER] [char](15) NULL,
	[FSK_CONDITION_PER] [int] NULL,
	[FK_CONDITION] [char](32) NULL,
	[IS_ORIGINAL] [char](1) NULL,
	[IS_ADDED] [char](1) NULL,
	[IS_SUM] [char](1) NULL,
	[LIM_COM] [char](30) NULL,
	[AMOUNT] [numeric](22, 0) NULL,
	[IS_UNLIMITED] [char](1) NULL,
	[LIMIT_PERCENT] [numeric](22, 5) NULL,
	[FRK_LIMIT_TYPE] [char](15) NULL,
	[FSK_LIMIT_TYPE] [int] NULL,
	[FK_CONDITION_PER] [char](32) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
