CREATE TABLE [staging].[PARTY_IDENTIFIER](
	[OBJECT_ID] [char](32) NOT NULL,
	[IDENTIFIER] [char](20) NULL,
	[FK_PARTY] [char](32) NULL,
	[FRK_PARTY_ID_TYPE] [char](15) NULL,
	[FSK_PARTY_ID_TYPE] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
