CREATE TABLE [staging].[PROTECTION_PRO_IBR](
	[OBJECT_ID] [char](32) NOT NULL,
	[FK_EVENT_CRE] [char](32) NULL,
	[FK_EVENT_REV] [char](32) NULL,
	[IS_CURRENT_OF_IP] [char](1) NULL,
	[IS_CURRENT_OF_LCP] [char](1) NULL,
	[FK_IBR_CONTAINER] [char](32) NULL,
	[IS_AUTO_REC_CALC] [char](1) NULL,
	[PROG_U_LMT] [numeric](25, 5) NULL,
	[PROG_L_LMT] [numeric](25, 5) NULL,
	[LIMIT_PCT_ORIG] [numeric](10, 6) NULL,
	[CUR_PART_START_TM] [datetime] NULL,
	[PART_SORT_VALUE] [int] NULL,
	[EXC_FR_PA_CL_ORD] [char](1) NULL,
	[FK_CURRENCY] [char](3) NULL,
	[FRK_INS_BASIS] [char](15) NULL,
	[FSK_INS_BASIS] [int] NULL,
	[FK_BUSCOND] [char](32) NULL,
	[FK_PROTECT_PART] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
