CREATE TABLE [staging].[PROTECT_PROG_PART](
	[OBJECT_ID] [char](32) NOT NULL,
	[REALISED] [char](1) NULL,
	[UPPER_LMT] [numeric](25, 5) NULL,
	[LOWER_LMT] [numeric](25, 5) NULL,
	[QS_PCT] [numeric](22, 2) NULL,
	[EXIST_START_TMSTMP] [datetime] NULL,
	[EXIST_END_TMSTMP] [datetime] NULL,
	[NBR_LINES] [numeric](14, 6) NULL,
	[LIABILITY_ONE_LINE] [numeric](22, 0) NULL,
	[LAYER_NUMBER] [int] NULL,
	[IS_UNLIMITED] [char](1) NULL,
	[SURPLUS_NUMBER] [int] NULL,
	[FK_PROT_IBR] [char](32) NULL,
	[FK_IP_OCC] [char](32) NULL,
	[FRK_TYPE_OF_BUS] [char](15) NULL,
	[FSK_TYPE_OF_BUS] [int] NULL,
	[FRK_TYPE_OF_PART] [char](15) NULL,
	[FSK_TYPE_OF_PART] [int] NULL,
	[FRK_TYPE_OF_COV] [char](15) NULL,
	[FSK_TYPE_OF_COV] [int] NULL,
	[FRK_LIMIT_TYPE] [char](15) NULL,
	[FSK_LIMIT_TYPE] [int] NULL,
	[FK_PARENTPART] [char](32) NULL,
	[FK_CLASSIFICATION] [char](32) NULL,
	[FK_CLA_OCC] [char](32) NULL,
	[SUBCLASS] [int] NULL,
	[FRK_AGREEMENT_TYPE] [char](15) NULL,
	[FSK_AGREEMENT_TYPE] [int] NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
