CREATE TABLE [staging].[REFERENCE_DATA](
	[CODE] [char](15) NOT NULL,
	[DATA_TYPE_CODE] [char](5) NULL,
	[IS_ACTIVE] [char](1) NULL,
	[IS_STATIC] [char](1) NULL,
	[IS_USER_DEFINED] [char](1) NULL,
	[IS_DEFAULT] [char](1) NULL,
	[NUMBER_OF_PERIODS] [int] NULL,
	[PERIOD_NUMBER] [int] NULL,
	[EXTERNAL_CODE] [char](50) NULL,
	[SUBCLASS] [int] NOT NULL,
	[NAME] [varchar](60) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC,
	[SUBCLASS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


