CREATE TABLE [staging].[RU_LEAF](
	[OBJECT_ID] [char](32) NOT NULL,
	[CODE] [char](12) NULL,
	[HIERARCHY_LEVEL] [int] NULL,
	[IS_ACTIVE] [char](1) NULL,
	[FK_NOTE] [char](32) NULL,
	[FRK_CATEGORY] [char](15) NULL,
	[FSK_CATEGORY] [int] NULL,
	[VERSION] [int] NULL,
	[NAME] [varchar](80) NULL,
	[UPPERCASE_NAME] [varchar](80) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
