CREATE TABLE [staging].[SOC_RU_RELATION](
	[OBJECT_ID] [char](32) NOT NULL,
	[CREATED_AT] [datetime] NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[FK_REPORTINGUNIT] [char](32) NULL,
	[FK_SOC] [char](32) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
