CREATE TABLE [staging].[SOC_TO_CLAIM_REL](
	[OBJECT_ID] [char](32) NOT NULL,
	[TO_BE_BOOKED] [char](1) NULL,
	[LAST_UPDATE_DT] [datetime] NULL,
	[CLAIM_ADVISED_DT] [datetime] NULL,
	[CLAIM_ACTION_DT] [datetime] NULL,
	[CL_REF] [char](30) NULL,
	[IS_INDEXED] [char](1) NULL,
	[IS_AGGR_DEDUCT] [char](1) NULL,
	[LAST_ADVISED_DT] [datetime] NULL,
	[NUM_OF_ADVISES] [int] NULL,
	[AMOUNT_POL_LIM] [numeric](20, 0) NULL,
	[AMOUNT_GR_UP] [numeric](20, 0) NULL,
	[AMOUNT_EX] [numeric](20, 0) NULL,
	[AMOUNT_OUR_GR_UP] [numeric](20, 0) NULL,
	[AMOUNT_MAX_IN] [numeric](20, 0) NULL,
	[ACCOUNT_YEAR] [int] NULL,
	[ID_SERIE_NO] [numeric](10, 0) NULL,
	[ID_PREFIX] [char](29) NULL,
	[ID_SUFFIX] [char](1) NULL,
	[IDENTIFIER] [char](36) NULL,
	[CLAIM_SHARE_FROM] [numeric](26, 7) NULL,
	[CLAIM_SHARE_FLD1] [numeric](26, 7) NULL,
	[CLAIM_SHARE_FLD2] [numeric](26, 7) NULL,
	[CLAIM_SHARE_FLD3] [numeric](26, 7) NULL,
	[CLAIM_BROK_ORD] [numeric](26, 7) NULL,
	[CLAIM_APPL_SHARE] [datetime] NULL,
	[CLAIM_COVER_AMNT] [numeric](22, 2) NULL,
	[CLAIM_OUR_SHARE] [numeric](22, 2) NULL,
	[CLAIM_EXC_AMNT] [numeric](22, 2) NULL,
	[CLAIM_APPL_LIMIT] [datetime] NULL,
	[IS_AUTO_IDX_CALC] [char](1) NULL,
	[IS_SEL_FGU_DED_RED] [char](1) NULL,
	[ADVICE_REC_DATE] [datetime] NULL,
	[AUTO_PA_BS_TIME] [datetime] NULL,
	[AUTO_PA_CL_TIME] [datetime] NULL,
	[FK_CLAIM] [char](32) NULL,
	[FK_SOC] [char](32) NULL,
	[FK_SUBST_SOC] [char](32) NULL,
	[FK_LAST_UPD_BY] [char](32) NULL,
	[FRK_STATUS_TYPE] [char](15) NULL,
	[FSK_STATUS_TYPE] [int] NULL,
	[FK_UDEF_DATA] [char](32) NULL,
	[FK_MAIN_CURR] [char](3) NULL,
	[FK_BASE_INDEX] [char](32) NULL,
	[FK_CLAIM_USER_SHR] [char](32) NULL,
	[FK_CLAIM_USER_LIM] [char](32) NULL,
	[FK_CLAIM_LIM_CCY] [char](3) NULL,
	[FRK_MC_REF_CONSQ] [char](15) NULL,
	[FSK_MC_REF_CONSQ] [int] NULL,
	[FRK_MC_REF_CAUSE] [char](15) NULL,
	[FSK_MC_REF_CAUSE] [int] NULL,
	[FK_CLPRG_PER_REL] [char](32) NULL,
	[FRK_COB] [char](15) NULL,
	[FSK_COB] [int] NULL,
	[FRK_MCOB] [char](15) NULL,
	[FSK_MCOB] [int] NULL,
	[FRK_INT_CAL_MTD] [char](15) NULL,
	[FSK_INT_CAL_MTD] [int] NULL,
	[ADV_AMT_CURR_AMT] [numeric](22, 2) NULL,
	[FK_ADV_AMT_CURR_CY] [char](3) NULL,
	[SUBCLASS] [int] NULL,
	[ACTION_COMMENT] [varchar](100) NULL,
	[BuildID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;
