CREATE TABLE [audit].[Fact_FinSnapshotSection] (
    [PK_Fact_FinSnapshotSection]          INT             NOT NULL,
    [FK_DateID]                           INT             NOT NULL,
    [FK_ContractID]                       INT             NOT NULL,
    [FK_CompanyID]                        INT             NOT NULL,
    [FK_LocationID]                       INT             NOT NULL,
    [FK_CedantLocationID]                 INT             NOT NULL,
    [FK_BrokerID]                         INT             NOT NULL,
    [FK_ReportingUnitID]                  INT             NOT NULL,
    [FK_BrokerContactID]                  INT             NOT NULL,
    [FK_CedantID]                         INT             NOT NULL,
    [FK_RITypeID]                         INT             NOT NULL,
    [FK_RIProgramID]                      INT             NOT NULL,
    [FK_DerivativeID]                     INT             NOT NULL,
    [FK_CurrencyID]                       INT             NOT NULL,
    [FK_Reporting_CurrencyID]             INT             NOT NULL,
    [GrossFinalPremiumAdjustment]         DECIMAL (38, 6) NULL,
    [GrossEarnedFinalPremiumAdjustment]   DECIMAL (38, 6) NULL,
    [GrossUnEarnedFinalPremiumAdjustment] DECIMAL (38, 6) NULL,
    [GrossNoClaimsBonus]                  DECIMAL (38, 6) NULL,
    [GrossEarnedNoClaimsBonus]            DECIMAL (38, 6) NULL,
    [GrossUnEarnedNoClaimsBonus]          DECIMAL (38, 6) NULL,
    [GrossPremium]                        DECIMAL (38, 6) NULL,
    [GrossEarnedPremium]                  DECIMAL (38, 6) NULL,
    [GrossUnEarnedPremium]                DECIMAL (38, 6) NULL,
    [GrossReinstatementPremium]           DECIMAL (38, 6) NULL,
    [GrossEarnedReinstatementPremium]     DECIMAL (38, 6) NULL,
    [GrossUnEarnedReinstatementPremium]   DECIMAL (38, 6) NULL,
    [GrossRoundingErrors]                 DECIMAL (38, 6) NULL,
    [GrossEarnedRoundingErrors]           DECIMAL (38, 6) NULL,
    [GrossUnEarnedRoundingErrors]         DECIMAL (38, 6) NULL,
    [CededFinalPremiumAdjustment]         DECIMAL (38, 6) NULL,
    [CededEarnedFinalPremiumAdjustment]   DECIMAL (38, 6) NULL,
    [CededUnEarnedFinalPremiumAdjustment] DECIMAL (38, 6) NULL,
    [CededNoClaimsBonus]                  DECIMAL (38, 6) NULL,
    [CededEarnedNoClaimsBonus]            DECIMAL (38, 6) NULL,
    [CededUnEarnedNoClaimsBonus]          DECIMAL (38, 6) NULL,
    [CededPremium]                        DECIMAL (38, 6) NULL,
    [CededEarnedPremium]                  DECIMAL (38, 6) NULL,
    [CededUnEarnedPremium]                DECIMAL (38, 6) NULL,
    [CededReinstatementPremium]           DECIMAL (38, 6) NULL,
    [CededEarnedReinstatementPremium]     DECIMAL (38, 6) NULL,
    [CededUnEarnedReinstatementPremium]   DECIMAL (38, 6) NULL,
    [CededRoundingErrors]                 DECIMAL (38, 6) NULL,
    [CededEarnedRoundingErrors]           DECIMAL (38, 6) NULL,
    [CededUnEarnedRoundingErrors]         DECIMAL (38, 6) NULL,
    [NetFinalPremiumAdjustment]           DECIMAL (38, 6) NULL,
    [NetEarnedFinalPremiumAdjustment]     DECIMAL (38, 6) NULL,
    [NetUnEarnedFinalPremiumAdjustment]   DECIMAL (38, 6) NULL,
    [NetNoClaimsBonus]                    DECIMAL (38, 6) NULL,
    [NetEarnedNoClaimsBonus]              DECIMAL (38, 6) NULL,
    [NetUnEarnedNoClaimsBonus]            DECIMAL (38, 6) NULL,
    [NetPremium]                          DECIMAL (38, 6) NULL,
    [NetEarnedPremium]                    DECIMAL (38, 6) NULL,
    [NetUnEarnedPremium]                  DECIMAL (38, 6) NULL,
    [NetReinstatementPremium]             DECIMAL (38, 6) NULL,
    [NetEarnedReinstatementPremium]       DECIMAL (38, 6) NULL,
    [NetUnEarnedReinstatementPremium]     DECIMAL (38, 6) NULL,
    [NetRoundingErrors]                   DECIMAL (38, 6) NULL,
    [NetEarnedRoundingErrors]             DECIMAL (38, 6) NULL,
    [NetUnEarnedRoundingErrors]           DECIMAL (38, 6) NULL,
    [Brokerage]                           DECIMAL (38, 6) NULL,
    [EarnedBrokerage]                     DECIMAL (38, 6) NULL,
    [UnEarnedBrokerage]                   DECIMAL (38, 6) NULL,
    [CedingCommission]                    DECIMAL (38, 6) NULL,
    [EarnedCedingCommission]              DECIMAL (38, 6) NULL,
    [UnEarnedCedingCommission]            DECIMAL (38, 6) NULL,
    [TSMFrontingFee]                      DECIMAL (38, 6) NULL,
    [EarnedTSMFrontingFee]                DECIMAL (38, 6) NULL,
    [UnEarnedTSMFrontingFee]              DECIMAL (38, 6) NULL,
    [FET]                                 DECIMAL (38, 6) NULL,
    [EarnedFET]                           DECIMAL (38, 6) NULL,
    [UnEarnedFET]                         DECIMAL (38, 6) NULL,
    [InterestonFundsHeld]                 DECIMAL (38, 6) NULL,
    [EarnedInterestonFundsHeld]           DECIMAL (38, 6) NULL,
    [UnEarnedInterestonFundsHeld]         DECIMAL (38, 6) NULL,
    [ProfitCommission]                    DECIMAL (38, 6) NULL,
    [EarnedProfitCommission]              DECIMAL (38, 6) NULL,
    [UnEarnedProfitCommission]            DECIMAL (38, 6) NULL,
    [CollateralOffsetFee]                 DECIMAL (38, 6) NULL,
    [EarnedCollateralOffsetFee]           DECIMAL (38, 6) NULL,
    [UnEarnedCollateralOffsetFee]         DECIMAL (38, 6) NULL,
    [DueDiligence]                        DECIMAL (38, 6) NULL,
    [EarnedDueDiligence]                  DECIMAL (38, 6) NULL,
    [UnEarnedDueDiligence]                DECIMAL (38, 6) NULL,
    [LeverageFees]                        DECIMAL (38, 6) NULL,
    [EarnedLeverageFees]                  DECIMAL (38, 6) NULL,
    [UnEarnedLeverageFees]                DECIMAL (38, 6) NULL,
    [OverridingCommission]                DECIMAL (38, 6) NULL,
    [EarnedOverridingCommission]          DECIMAL (38, 6) NULL,
    [UnEarnedOverridingCommission]        DECIMAL (38, 6) NULL,
    [OtherExpenses]                       DECIMAL (38, 6) NULL,
    [EarnedOtherExpenses]                 DECIMAL (38, 6) NULL,
    [UnEarnedOtherExpenses]               DECIMAL (38, 6) NULL,
    [OtherIncome]                         DECIMAL (38, 6) NULL,
    [EarnedOtherIncome]                   DECIMAL (38, 6) NULL,
    [UnEarnedOtherIncome]                 DECIMAL (38, 6) NULL,
    [TSMManagementFee]                    DECIMAL (38, 6) NULL,
    [EarnedTSMManagementFee]              DECIMAL (38, 6) NULL,
    [UnEarnedTSMManagementFee]            DECIMAL (38, 6) NULL,
    [SPC]                                 DECIMAL (38, 6) NULL,
    [EarnedSPC]                           DECIMAL (38, 6) NULL,
    [UnEarnedSPC]                         DECIMAL (38, 6) NULL,
    [OtherTax]                            DECIMAL (38, 6) NULL,
    [EarnedOtherTax]                      DECIMAL (38, 6) NULL,
    [UnEarnedOtherTax]                    DECIMAL (38, 6) NULL,
    [Unclassified]                        DECIMAL (38, 6) NULL,
    [EarnedUnclassified]                  DECIMAL (38, 6) NULL,
    [UnEarnedUnclassified]                DECIMAL (38, 6) NULL,
    [AustralianWitholdingTax]             DECIMAL (38, 6) NULL,
    [EarnedAustralianWitholdingTax]       DECIMAL (38, 6) NULL,
    [UnEarnedAustralianWitholdingTax]     DECIMAL (38, 6) NULL,
    [FundsHeld]                           DECIMAL (38, 6) NULL,
    [EarnedFundsHeld]                     DECIMAL (38, 6) NULL,
    [UnEarnedFundsHeld]                   DECIMAL (38, 6) NULL,
    [GSTBrokerage]                        DECIMAL (38, 6) NULL,
    [EarnedGSTBrokerage]                  DECIMAL (38, 6) NULL,
    [UnEarnedGSTBrokerage]                DECIMAL (38, 6) NULL,
    [GSTPremium]                          DECIMAL (38, 6) NULL,
    [EarnedGSTPremium]                    DECIMAL (38, 6) NULL,
    [UnEarnedGSTPremium]                  DECIMAL (38, 6) NULL,
    [RetroFET]                            DECIMAL (38, 6) NULL,
    [EarnedRetroFET]                      DECIMAL (38, 6) NULL,
    [UnEarnedRetroFET]                    DECIMAL (38, 6) NULL,
    [PaidLAE]                             DECIMAL (38, 6) NULL,
    [EarnedPaidLAE]                       DECIMAL (38, 6) NULL,
    [UnEarnedPaidLAE]                     DECIMAL (38, 6) NULL,
    [AssuemdPremium]                      DECIMAL (38, 6) NULL,
    [UnFXEst]                             DECIMAL (38, 6) NULL,
    [ReValuedUnFXEst]                     DECIMAL (38, 6) NULL,
    [ReValuedUnFXEstUGLO]                 DECIMAL (38, 6) NULL,
    [FXRate]                              DECIMAL (15, 8) NULL,
    [GrossLossesPaidBal]                  DECIMAL (15, 2) NULL,
    [CededLossesPaidBal]                  DECIMAL (15, 2) NULL,
    [NetLossesPaidBal]                    DECIMAL (15, 2) NULL,
    [GrossCaseReserveBal]                 DECIMAL (15, 2) NULL,
    [CededCaseReserveBal]                 DECIMAL (15, 2) NULL,
    [NetCaseReserveBal]                   DECIMAL (15, 2) NULL,
    [GrossIBNRBal]                        DECIMAL (15, 2) NULL,
    [CededIBNRBal]                        DECIMAL (15, 2) NULL,
    [NetIBNRBal]                          DECIMAL (15, 2) NULL,
    [GrossACRBal]                         DECIMAL (15, 2) NULL,
    [CededACRBal]                         DECIMAL (15, 2) NULL,
    [NetACRBal]                           DECIMAL (15, 2) NULL,
    [GrossUnclassedAmtBal]                DECIMAL (15, 2) NULL,
    [CededUnclassedAmtBal]                DECIMAL (15, 2) NULL,
    [NetUnclassedAmtBal]                  DECIMAL (15, 2) NULL,
    [UGLO_ITD]                            DECIMAL (15, 2) NULL,
    [UGLO_YTD]                            DECIMAL (15, 2) NULL,
    [UGLO_QTD]                            DECIMAL (15, 2) NULL,
    [UGLO_MTD]                            DECIMAL (15, 2) NULL,
    [UGLO_FTD]                            DECIMAL (15, 2) NULL,
    [NetLossesIncurred_ITD]               DECIMAL (15, 2) NULL,
    [NetLossesIncurred_YTD]               DECIMAL (15, 2) NULL,
    [NetLossesIncurred_QTD]               DECIMAL (15, 2) NULL,
    [NetLossesIncurred_MTD]               DECIMAL (15, 2) NULL,
    [NetLossesIncurred_FTD]               DECIMAL (15, 2) NULL,
    [EffectiveFromDate]                   DATE            NULL,
    [EffectiveToDate]                     DATE            NULL,
    [CurrentFlag]                         NVARCHAR (1)    NULL
);

